spring:
    # 环境 dev:开发环境|test:测试环境|prod:生产环境
    profiles:
        active: dev #激活的配置文件


spring:
  profiles: dev                      #开发环境
  application:
      name: cloud-config-dev


spring:
  profiles: test                    #测试环境
  application:
       name: cloud-config-test


#请保存为utf-8
  
   